#!/usr/bin/env node
/**
 * Generates a reviewable PostgreSQL DDL file from prisma/schema.prisma (offline — no database or
 * Prisma engine needed; uses @prisma/prisma-schema-wasm).
 *
 *   node scripts/gen-ddl.js > sql/001_schema.sql
 *
 * The output follows Prisma's own naming (tables "Model", indexes Model_a_b_idx, FK Model_col_fkey),
 * so it is interchangeable with what `prisma migrate dev` generates. Re-run it whenever schema.prisma
 * changes and commit the result.
 */
const fs = require('fs');
const path = require('path');
const wasm = require('@prisma/prisma-schema-wasm');

const schemaPath = path.join(__dirname, '..', 'prisma', 'schema.prisma');
const schemaText = fs.readFileSync(schemaPath, 'utf8');
const dmmf = JSON.parse(wasm.get_dmmf(JSON.stringify({ prismaSchema: schemaText, noColor: true }))).datamodel;

// ── native types (@db.X(...)) are not exposed by get_dmmf → read them from the schema text ──
const native = {};
for (const m of schemaText.matchAll(/^model (\w+) \{([\s\S]*?)^\}/gm)) {
  for (const line of m[2].split('\n')) {
    const f = line.match(/^\s+(\w+)\s+\S+.*?@db\.(\w+)(?:\(([^)]*)\))?/);
    if (f) native[`${m[1]}.${f[1]}`] = { type: f[2], args: f[3] ? f[3].split(',').map(s => s.trim()) : [] };
  }
}

const q = (s) => `"${s}"`;
const enumNames = new Set(dmmf.enums.map(e => e.name));

function sqlType(model, field) {
  if (field.kind === 'enum') return q(field.type);
  const n = native[`${model}.${field.name}`];
  switch (field.type) {
    case 'String':   if (n?.type === 'Char') return `CHAR(${n.args[0]})`; if (n?.type === 'VarChar') return `VARCHAR(${n.args[0]})`; return 'TEXT';
    case 'Int':      return 'INTEGER';
    case 'BigInt':   return 'BIGINT';
    case 'Boolean':  return 'BOOLEAN';
    case 'DateTime': return n?.type === 'Date' ? 'DATE' : 'TIMESTAMP(3)';
    case 'Decimal':  return n?.type === 'Decimal' ? `DECIMAL(${n.args.join(',')})` : 'DECIMAL(65,30)';
    case 'Json':     return 'JSONB';
    case 'Float':    return 'DOUBLE PRECISION';
    default: throw new Error(`Unsupported type ${field.type} on ${model}.${field.name}`);
  }
}

function sqlDefault(field) {
  if (!field.hasDefaultValue || field.default === undefined) return '';
  const d = field.default;
  if (typeof d === 'object' && d !== null && !Array.isArray(d)) {
    if (d.name === 'now') return ' DEFAULT CURRENT_TIMESTAMP';
    if (d.name === 'uuid(4)' || d.name === 'uuid' || d.name === 'cuid') return ''; // generated by the Prisma client
    throw new Error(`Unsupported default fn ${d.name} on ${field.name}`);
  }
  if (field.kind === 'enum') return ` DEFAULT '${d}'`;
  if (field.type === 'Boolean') return ` DEFAULT ${d ? 'true' : 'false'}`;
  if (field.type === 'Int' || field.type === 'Decimal' || field.type === 'Float') return ` DEFAULT ${d}`;
  if (field.type === 'Json') return ` DEFAULT '${String(d).replace(/'/g, "''")}'::jsonb`;
  return ` DEFAULT '${String(d).replace(/'/g, "''")}'`;
}

const out = [];
out.push('-- GENERATED by scripts/gen-ddl.js from prisma/schema.prisma — do not edit by hand.');
out.push('-- Target: PostgreSQL 14+. Apply with: psql "$DATABASE_URL" -f sql/001_schema.sql\n');

for (const e of dmmf.enums) {
  out.push(`CREATE TYPE ${q(e.name)} AS ENUM (${e.values.map(v => `'${v.name}'`).join(', ')});`);
}
out.push('');

for (const m of dmmf.models) {
  const cols = [];
  for (const f of m.fields) {
    if (f.kind === 'object') continue;
    cols.push(`  ${q(f.name)} ${sqlType(m.name, f)}${f.isRequired ? ' NOT NULL' : ''}${sqlDefault(f)}`);
  }
  const pk = m.fields.filter(f => f.isId).map(f => q(f.name));
  if (pk.length) cols.push(`  CONSTRAINT ${q(m.name + '_pkey')} PRIMARY KEY (${pk.join(', ')})`);
  out.push(`CREATE TABLE ${q(m.name)} (\n${cols.join(',\n')}\n);\n`);
}

// indexes (unique + normal)
for (const ix of dmmf.datamodel?.indexes || dmmf.indexes) {
  if (ix.type === 'id') continue;
  const names = ix.fields.map(f => f.name).join('_');
  const cols = ix.fields.map(f => q(f.name) + (f.sortOrder === 'desc' ? ' DESC' : '')).join(', ');
  if (ix.type === 'unique') out.push(`CREATE UNIQUE INDEX ${q(`${ix.model}_${names}_key`)} ON ${q(ix.model)}(${cols});`);
  else out.push(`CREATE INDEX ${q(`${ix.model}_${names}_idx`)} ON ${q(ix.model)}(${cols});`);
}
out.push('');

// foreign keys
for (const m of dmmf.models) {
  for (const f of m.fields) {
    if (f.kind !== 'object' || !f.relationFromFields?.length) continue;
    const onDelete = ({ Cascade: 'CASCADE', Restrict: 'RESTRICT', SetNull: 'SET NULL', NoAction: 'NO ACTION' })[f.relationOnDelete]
      || (f.isRequired ? 'RESTRICT' : 'SET NULL');
    out.push(`ALTER TABLE ${q(m.name)} ADD CONSTRAINT ${q(`${m.name}_${f.relationFromFields.join('_')}_fkey`)} FOREIGN KEY (${f.relationFromFields.map(q).join(', ')}) REFERENCES ${q(f.type)}(${f.relationToFields.map(q).join(', ')}) ON DELETE ${onDelete} ON UPDATE CASCADE;`);
  }
}

process.stdout.write(out.join('\n') + '\n');
